version: '3.1'
services:
  bookdb:
    image: postgres
    container_name: db
    networks:
      - loyalty-program-network
    environment:
      - POSTGRES_USER=bookuser
      - POSTGRES_PASSWORD=bookpassword
      - POSTGRES_DB=bookdb
      - PGDATA=/var/lib/postgresql/data/dbdata
    ports:
      - "5432:5432"
      - "5700:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
volumes:
  dbdata:
  service_volume:
networks:
  loyalty-program-network:
